version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: foot3000_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foot3000db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foot3000_app
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
